name: latitude-blue-2.0
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40 

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/brave-browser.repo
        - https://copr.fedorainfracloud.org/coprs/atim/zerotier-one/repo/fedora-40/atim-zerotier-one-fedora-40.repo
    install:
        - eza
        - zerotier-one
        - zsh
        - neovim
        - easyeffects
        - pavucontrol
        - brave-browser
    optfix:
        - brave.com
    remove:
        - firefox
        - firefox-langpacks
        - filelight

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.visualstudio.code
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - com.stremio.Stremio
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.sindresorhus.Caprine
        - com.bitwarden.desktop

  - type: signing
