name: latitude-blue-2.0
description: This is my personal OS image.


base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
        - https://copr.fedorainfracloud.org/coprs/atim/zerotier-one/repo/fedora-40/atim-zerotier-one-fedora-40.repo
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/nordvpn.repo
    install:
        - plymouth
        - chromium
        - eza
        - zerotier-one
        - zsh
        - neovim
        - easyeffects
        - pavucontrol
        - nordvpn
    remove:

  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - cafe.avery.Delfin
        - com.nordpass.NordPass
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - com.stremio.Stremio
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.sindresorhus.Caprine
  - type: script
    scripts:
        - chromium.sh
  - type: signing
